from enum import Enum


class DengueColumns(Enum):
    DATA = "Data"
    IDADE = "Idade"
    FAIXA_ETARIA = "Faixa Etária"
    GENERO = "Gênero"
    ESCOLARIDADE = "Escolaridade"
    OCUPACAO = "Ocupação"
    RENDA = "Renda"
    N_CONTAGIO = "N Contágio"
    FAMILIAR_CONTAGIO = "Familiar Contágio"
    ESTADO = "Estado"
    CIDADE = "Cidade"
    BAIRRO = "Bairro"
    REGIAO = "Região"
    MORADIA = "Moradia"
    N_COABITACAO = "N Coabitação"
    FONTE_INFORMACAO = "Fonte Informação"
    MICRORGANISMO = "Microrganismo"
    NOTA_MICRORGANISMO = "Nota Microrganismo"
    FORMAS_CONTAGIO = "Formas Contágio"
    NOTA_CONTAGIO = "Nota Contágio"
    SINTOMAS = "Sintomas"
    NOTA_SINTOMAS = "Nota Sintomas"
    PREVENCAO = "Prevenção"
    NOTA_PREVENCAO = "Nota Prevenção"
    COMBATE = "Combate"
    NOTA_COMBATE = "Nota Combate"
    NOTA_FINAL = "Nota Final"
    AVALIACAO_TRATAMENTO = "Avaliação Tratamento"
    SANEAMENTO = "Saneamento"
    GOV_COMBATE = "Gov. Combate"
    FREQUENCIA_ACOES_PREVENCAO = "Freq. Ações Prevenção"
    PREOCUPACAO = "Preocupação"
    VACINACAO_SUS = "Vacinação SUS"
